In [19]:
import numpy as np
import pandas as pd

import torch
import torchvision
from torch.utils.data import Dataset, DataLoader


from tqdm import tqdm

from PIL import Image

In [15]:
import os
import glob

In [17]:
data_directory = '/workspace/processed_data'
tif_files = glob.glob(os.path.join(data_directory, '**', '*.tif'), recursive=True)

In [57]:
print(len(tif_files))

6013


In [45]:
class ImageData(Dataset):
    
    def __init__(self):
        super().__init__()
        self.file_paths = tif_files
    
    def __len__(self):
        return len(self.file_paths)
    
    def __getitem__(self, idx):
        
        # import
        file_path = self.file_paths[idx]        
        with Image.open(file_path) as img:
                data = np.array(img).astype('float32') 

        return data


In [46]:
image_dataset = ImageData()
image_loader = DataLoader(image_dataset, 
                          batch_size  = 1, 
                          shuffle     = False, 
                          num_workers = 0)

In [ ]:
mean    = torch.tensor([0.0])
var = torch.tensor([0.0])
minimum = torch.tensor([0.0])
maximum = torch.tensor([0.0])

# loop through images
for inputs in tqdm(image_loader):
    if torch.any(inputs < 0):
        continue
    imgmean = torch.mean(inputs)
    print(imgmean)
    imgvar = torch.var(inputs)
    mean += (imgmean / len(tif_files))
    var += (imgvar / len(tif_files))

p_sqrt = torch.sqrt(var)

In [66]:
print(mean)
print(var)
print(p_sqrt)

tensor([67805.0391])
tensor([1.1258e+14])
tensor([10610533.])
